# init_pos
#   pos: [0, 0, 2.0]
#   ori: 
#   target ?

gates:
  - id: 1
    pos: [-1.0, 1.25, 2.0]        # [x, y, z]
    ori: [0.0, 0.0, 90]         # [roll, pitch, yaw] 
    visible: true

  - id: 2
    pos: [9.0, 6.0, 2.0]
    ori: [0.0, 0.0, -15]      
    visible: true

  - id: 3
    pos: [9.0, -3.0, 2.0]
    ori: [0.0, 0.0, 45]         
    visible: true

  - id: 4
    pos: [-5.0,-7.0, 4.0]
    ori: [0.0, 0.0, 90]     
    visible: true

  - id: 5
    pos: [-5.0, -7.0, 2.0]
    ori: [0.0, 0.0, -90]     
    visible: true

  - id: 6
    pos: [4.0, -1.0, 2.0]
    ori: [0.0, 0.0, 35]       
    visible: true

  - id: 7
    pos: [-2.5, 6.5, 2.0]
    ori: [0.0, 0.0, 15]     
    visible: true